import type { Metadata } from "next";
import Header from "./_components/Header/Header";
import Footer from "./_components/Footer/Footer";

export const metadata: Metadata = {
  title: "WadaExpress",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Header />
      <div className="wrapper mx-auto max-w-[1320px] font-normal text-gray-900 px-[80px] 2xl:px-0">
        {children}
      </div>
      <Footer />
    </>
  );
}
